name: Build

on:
  push:
    branches:
      - main # Trigger on push to main branch (e.g., when a PR is merged)
  pull_request:
    branches:
      - main # Trigger on pull request activities targeting the main branch

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22.0"

      - run: go version

      - name: Build
        run: make build
